### PR TITLE
feat(actions): also test doc build on pull requests

### PR DESCRIPTION
**Pull request by skjnldsv**
~~@ChristophWurst do you know why `@nextcloud/l10n` is failing ?~~

### CODE REVIEW

**Comment by susnux** [comment]
@skjnldsv I think because the `@nextcloud/typings` is not installed. It is just a dev dependency of `l10n` and no dependency of `nextcloud-files`.
I think either adding it is as a dev dependency of `nextcloud-files` or a (peer) dependency of `l10n` will fix this issue.

**Comment by skjnldsv** [comment]
@susnux well done! :rocket: :pray:

**Review by susnux — APPROVED** [review]
Probably we should still add it is as a (peer) dependency to `l10n` but until then this is fine :+1:

**Comment by skjnldsv** [comment]
> Probably we should still add it is as a (peer) dependency to `l10n` but until then this is fine +1

Hum, that's actually more correct. This doesn't belong here :see_no_evil:

**Pull request merged**
