### PR TITLE
Fix decimal prefixes and add option for binary prefixes per IEC 80000-13

### PR DESCRIPTION
**Pull request by Zipdox**
Also added pebibyte

Fixes https://github.com/nextcloud/server/issues/35464

Signed-off-by: Zipdox <42157341+Zipdox@users.noreply.github.com>

### CODE REVIEW

**Comment by Zipdox** [comment]
Ideally there would be an option to choose between decimal and binary prefixes but that would require adding it to the settings as well which is beyond my expertise.

**Review by skjnldsv — DISMISSED** [review]

**Comment by nickvergessen** [comment]
I gave up on the KiB vs KB discussions. There was an issue with hundreds of comments at some point and also several PRs on documentation to replace them all. But I think it was agreed to stay as is.

**Comment by skjnldsv** [comment]
@jancborchardt and @nextcloud/desktop for the display parity

**Comment by Zipdox** [comment]
I had a negative interaction with Mozilla devs about this same issue in Firefox. They didn't want to change it because this is the "traditional way" or whatever. This change doesn't change the actual counting of bytes. The numbers stay the same. It just applies the proper prefix. If someone has a problem with that then they should stop being stubborn and ignorant and grow up.

**Comment by skjnldsv** [comment]
> If someone has a problem with that then they should stop being stubborn and ignorant and grow up.

Aaaand, bingo! Please have a look at our code of conduct. This is not how we discuss about things at Nextcloud. https://nextcloud.com/contribute/code-of-conduct/

Do not call people names because they have a different opinion on the subject than you do. This is your first and only warning. Let others react and give people time if you want to keep this topic active. Period.

**Review by elsiehupp — DISMISSED** [review]
See my comments about an alternate approach [here](https://github.com/nextcloud/server/issues/35464#issuecomment-1344341690). (I'm adding this review as a hook for a new thread.)

**Comment by elsiehupp** [comment]
(I'm not comfortable unilaterally merging this, since I'm not a regular maintainer on this repository. One of the regular maintainers can submit a review for the merge.)

**Comment by elsiehupp** [comment]
> (I'm not comfortable unilaterally merging this, since I'm not a regular maintainer on this repository. One of the regular maintainers can submit a review for the merge.)

On reflection, I would be willing to approve these changes if no one objects in the week or two. Feel free to re-request my review if no one else responds!

**Review by elsiehupp — APPROVED** [review]

**Pull request merged**
